app:
    resource: "@AppBundle/Controller"
    type: annotation
logout:
    path: /logout
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
